/*globals define, WebGMEGlobal*/

/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Sun Dec 01 2024 15:23:06 GMT-0700 (Mountain Standard Time).
 */

define(['css!./styles/SVGViewWidget.css'], function () {
    'use strict';

    var WIDGET_CLASS = 's-v-g-view';

    function SVGViewWidget(logger, container) {
        this._logger = logger.fork('Widget');

        this._el = container;

        this.nodes = {}
        this._initialize();

        this._logger.debug('ctor finished');
    }

    SVGViewWidget.prototype._initialize = function () {
        var width = this._el.width(),
            height = this._el.height(),
            self = this;

        // set widget class
        this._el.addClass(WIDGET_CLASS);
        this._iframe = null;

    };

    SVGViewWidget.prototype.onWidgetContainerResize = function (width, height) {
        this._logger.debug('Widget is resizing...');
    };

    SVGViewWidget.prototype.initNode = function (hash, path) {
        var iframe = document.createElement('iframe');
        iframe.name = "TurtleSVG";
        iframe.style.height = "100%";
        iframe.style.width = "100%";
        iframe.src = '/extlib/src/common/svg/' + hash.replace('#','_') + '_' + path.replace('/','_') + '.svg';

        this._el.append(iframe);
        this._iframe = iframe;
    };

    SVGViewWidget.prototype.refresh = function () {
        this._iframe.contentWindow.location.reload(true);
    }

    /* * * * * * * * Visualizer life cycle callbacks * * * * * * * */
    SVGViewWidget.prototype.destroy = function () {
    };

    SVGViewWidget.prototype.onActivate = function () {
        this._logger.debug('SVGViewWidget has been activated');
    };

    SVGViewWidget.prototype.onDeactivate = function () {
        this._logger.debug('SVGViewWidget has been deactivated');
    };

    return SVGViewWidget;
});
